sonar.projectKey=ST10363752_customer-payments-portal
sonar.projectName=customer-payments-portal
sonar.projectVersion=1.0
sonar.organization=st10363752
sonar.sources=server,client/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js
sonar.javascript.lcov.reportPaths=
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300