version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Install Client Dependencies
          command: |
            cd client
            npm install --force
      - run:
          name: Build Frontend
          command: |
            cd client
            npm run build
      - run:
          name: Verify Backend Syntax
          command: |
            cd server
            node -c index.js
      - sonarcloud/scan:
          name: SonarQube Scan
          project_key: ST10363752_customer-payments-portal
          project_name: customer-payments-portal

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build